//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.29 at 07:49:17 PM EET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://drachyova.it.by/jd02_09/Hotel", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package by.it.drachyova.jd02_09.TaskC;
