//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.07.03 at 01:14:11 AM GMT+02:00 
//


package by.it.luksha.jd02_09.taskB;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Address">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Geoaddress">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="Country" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="City" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="Street" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="Webaddress">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="Site" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
 *                             &lt;element name="Email" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="Phone" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="ListCars">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Car" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="Price">
 *                               &lt;complexType>
 *                                 &lt;simpleContent>
 *                                   &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                                     &lt;attribute name="currency" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                   &lt;/extension>
 *                                 &lt;/simpleContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="Brand" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="Model">
 *                               &lt;complexType>
 *                                 &lt;simpleContent>
 *                                   &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                                     &lt;attribute name="category" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                   &lt;/extension>
 *                                 &lt;/simpleContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="Gearbox" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="Engine">
 *                               &lt;complexType>
 *                                 &lt;simpleContent>
 *                                   &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                                     &lt;attribute name="volume" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                   &lt;/extension>
 *                                 &lt;/simpleContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="Places" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="AirCool" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="Isofix" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "name",
    "address",
    "listCars"
})
@XmlRootElement(name = "CarRent")
public class CarRent {
    @Override
    public String toString() {
        return String.format("Name: %s Address: %s ListCars: %s\n", name, address, listCars);
    }

    @XmlElement(name = "Name", required = true)
    protected String name;
    @XmlElement(name = "Address", required = true)
    protected CarRent.Address address;
    @XmlElement(name = "ListCars", required = true)
    protected CarRent.ListCars listCars;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the address property.
     * 
     * @return
     *     possible object is
     *     {@link CarRent.Address }
     *     
     */
    public CarRent.Address getAddress() {
        return address;
    }

    /**
     * Sets the value of the address property.
     * 
     * @param value
     *     allowed object is
     *     {@link CarRent.Address }
     *     
     */
    public void setAddress(CarRent.Address value) {
        this.address = value;
    }

    /**
     * Gets the value of the listCars property.
     * 
     * @return
     *     possible object is
     *     {@link CarRent.ListCars }
     *     
     */
    public CarRent.ListCars getListCars() {
        return listCars;
    }

    /**
     * Sets the value of the listCars property.
     * 
     * @param value
     *     allowed object is
     *     {@link CarRent.ListCars }
     *     
     */
    public void setListCars(CarRent.ListCars value) {
        this.listCars = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Geoaddress">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="Country" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="City" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="Street" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="Webaddress">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="Site" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
     *                   &lt;element name="Email" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="Phone" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "geoaddress",
        "webaddress",
        "phone"
    })
    public static class Address {
        @Override
        public String toString() {
            return String.format("Geo: %s Web: %s Phone: %s\n", geoaddress, webaddress, phone);
        }

        @XmlElement(name = "Geoaddress", required = true)
        protected CarRent.Address.Geoaddress geoaddress;
        @XmlElement(name = "Webaddress", required = true)
        protected CarRent.Address.Webaddress webaddress;
        @XmlElement(name = "Phone", required = true)
        protected String phone;

        /**
         * Gets the value of the geoaddress property.
         * 
         * @return
         *     possible object is
         *     {@link CarRent.Address.Geoaddress }
         *     
         */
        public CarRent.Address.Geoaddress getGeoaddress() {
            return geoaddress;
        }

        /**
         * Sets the value of the geoaddress property.
         * 
         * @param value
         *     allowed object is
         *     {@link CarRent.Address.Geoaddress }
         *     
         */
        public void setGeoaddress(CarRent.Address.Geoaddress value) {
            this.geoaddress = value;
        }

        /**
         * Gets the value of the webaddress property.
         * 
         * @return
         *     possible object is
         *     {@link CarRent.Address.Webaddress }
         *     
         */
        public CarRent.Address.Webaddress getWebaddress() {
            return webaddress;
        }

        /**
         * Sets the value of the webaddress property.
         * 
         * @param value
         *     allowed object is
         *     {@link CarRent.Address.Webaddress }
         *     
         */
        public void setWebaddress(CarRent.Address.Webaddress value) {
            this.webaddress = value;
        }

        /**
         * Gets the value of the phone property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPhone() {
            return phone;
        }

        /**
         * Sets the value of the phone property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPhone(String value) {
            this.phone = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="Country" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="City" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="Street" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "country",
            "city",
            "street"
        })
        public static class Geoaddress {
            @Override
            public String toString() {
                return String.format("Country: %s; City: %s; Street: %s\n", country, city, street);
            }

            @XmlElement(name = "Country", required = true)
            protected String country;
            @XmlElement(name = "City", required = true)
            protected String city;
            @XmlElement(name = "Street", required = true)
            protected String street;

            /**
             * Gets the value of the country property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCountry() {
                return country;
            }

            /**
             * Sets the value of the country property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCountry(String value) {
                this.country = value;
            }

            /**
             * Gets the value of the city property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCity() {
                return city;
            }

            /**
             * Sets the value of the city property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCity(String value) {
                this.city = value;
            }

            /**
             * Gets the value of the street property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getStreet() {
                return street;
            }

            /**
             * Sets the value of the street property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setStreet(String value) {
                this.street = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="Site" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
         *         &lt;element name="Email" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "site",
            "email"
        })
        public static class Webaddress {
            @Override
            public String toString() {
                return String.format("Site: %s; Email: %s\n", site, email);
            }

            @XmlElement(name = "Site", required = true)
            @XmlSchemaType(name = "anyURI")
            protected String site;
            @XmlElement(name = "Email", required = true)
            protected String email;

            /**
             * Gets the value of the site property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getSite() {
                return site;
            }

            /**
             * Sets the value of the site property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setSite(String value) {
                this.site = value;
            }

            /**
             * Gets the value of the email property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getEmail() {
                return email;
            }

            /**
             * Sets the value of the email property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setEmail(String value) {
                this.email = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Car" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="Price">
     *                     &lt;complexType>
     *                       &lt;simpleContent>
     *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *                           &lt;attribute name="currency" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                         &lt;/extension>
     *                       &lt;/simpleContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="Brand" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="Model">
     *                     &lt;complexType>
     *                       &lt;simpleContent>
     *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *                           &lt;attribute name="category" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                         &lt;/extension>
     *                       &lt;/simpleContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="Gearbox" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="Engine">
     *                     &lt;complexType>
     *                       &lt;simpleContent>
     *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *                           &lt;attribute name="volume" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                         &lt;/extension>
     *                       &lt;/simpleContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="Places" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="AirCool" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="Isofix" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "car"
    })
    public static class ListCars {

        @XmlElement(name = "Car")
        protected List<CarRent.ListCars.Car> car;

        /**
         * Gets the value of the car property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the car property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getCar().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link CarRent.ListCars.Car }
         * 
         * 
         */
        public List<CarRent.ListCars.Car> getCar() {
            if (car == null) {
                car = new ArrayList<CarRent.ListCars.Car>();
            }
            return this.car;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="Price">
         *           &lt;complexType>
         *             &lt;simpleContent>
         *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
         *                 &lt;attribute name="currency" type="{http://www.w3.org/2001/XMLSchema}string" />
         *               &lt;/extension>
         *             &lt;/simpleContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="Brand" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="Model">
         *           &lt;complexType>
         *             &lt;simpleContent>
         *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
         *                 &lt;attribute name="category" type="{http://www.w3.org/2001/XMLSchema}string" />
         *               &lt;/extension>
         *             &lt;/simpleContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="Gearbox" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="Engine">
         *           &lt;complexType>
         *             &lt;simpleContent>
         *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
         *                 &lt;attribute name="volume" type="{http://www.w3.org/2001/XMLSchema}string" />
         *               &lt;/extension>
         *             &lt;/simpleContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="Places" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="AirCool" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="Isofix" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "price",
            "brand",
            "model",
            "gearbox",
            "engine",
            "places",
            "airCool",
            "isofix"
        })
        public static class Car {

            @XmlElement(name = "Price", required = true)
            protected CarRent.ListCars.Car.Price price;
            @XmlElement(name = "Brand", required = true)
            protected String brand;
            @XmlElement(name = "Model", required = true)
            protected CarRent.ListCars.Car.Model model;
            @XmlElement(name = "Gearbox", required = true)
            protected String gearbox;
            @XmlElement(name = "Engine", required = true)
            protected CarRent.ListCars.Car.Engine engine;
            @XmlElement(name = "Places", required = true)
            protected String places;
            @XmlElement(name = "AirCool", required = true)
            protected String airCool;
            @XmlElement(name = "Isofix", required = true)
            protected String isofix;

            /**
             * Gets the value of the price property.
             * 
             * @return
             *     possible object is
             *     {@link CarRent.ListCars.Car.Price }
             *     
             */
            public CarRent.ListCars.Car.Price getPrice() {
                return price;
            }

            /**
             * Sets the value of the price property.
             * 
             * @param value
             *     allowed object is
             *     {@link CarRent.ListCars.Car.Price }
             *     
             */
            public void setPrice(CarRent.ListCars.Car.Price value) {
                this.price = value;
            }

            /**
             * Gets the value of the brand property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getBrand() {
                return brand;
            }

            /**
             * Sets the value of the brand property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setBrand(String value) {
                this.brand = value;
            }

            /**
             * Gets the value of the model property.
             * 
             * @return
             *     possible object is
             *     {@link CarRent.ListCars.Car.Model }
             *     
             */
            public CarRent.ListCars.Car.Model getModel() {
                return model;
            }

            /**
             * Sets the value of the model property.
             * 
             * @param value
             *     allowed object is
             *     {@link CarRent.ListCars.Car.Model }
             *     
             */
            public void setModel(CarRent.ListCars.Car.Model value) {
                this.model = value;
            }

            /**
             * Gets the value of the gearbox property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getGearbox() {
                return gearbox;
            }

            /**
             * Sets the value of the gearbox property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setGearbox(String value) {
                this.gearbox = value;
            }

            /**
             * Gets the value of the engine property.
             * 
             * @return
             *     possible object is
             *     {@link CarRent.ListCars.Car.Engine }
             *     
             */
            public CarRent.ListCars.Car.Engine getEngine() {
                return engine;
            }

            /**
             * Sets the value of the engine property.
             * 
             * @param value
             *     allowed object is
             *     {@link CarRent.ListCars.Car.Engine }
             *     
             */
            public void setEngine(CarRent.ListCars.Car.Engine value) {
                this.engine = value;
            }

            /**
             * Gets the value of the places property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPlaces() {
                return places;
            }

            /**
             * Sets the value of the places property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setPlaces(String value) {
                this.places = value;
            }

            /**
             * Gets the value of the airCool property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getAirCool() {
                return airCool;
            }

            /**
             * Sets the value of the airCool property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setAirCool(String value) {
                this.airCool = value;
            }

            /**
             * Gets the value of the isofix property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getIsofix() {
                return isofix;
            }

            /**
             * Sets the value of the isofix property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setIsofix(String value) {
                this.isofix = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;simpleContent>
             *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
             *       &lt;attribute name="volume" type="{http://www.w3.org/2001/XMLSchema}string" />
             *     &lt;/extension>
             *   &lt;/simpleContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "value"
            })
            public static class Engine {

                @XmlValue
                protected String value;
                @XmlAttribute(name = "volume")
                protected String volume;

                /**
                 * Gets the value of the value property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getValue() {
                    return value;
                }

                /**
                 * Sets the value of the value property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setValue(String value) {
                    this.value = value;
                }

                /**
                 * Gets the value of the volume property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getVolume() {
                    return volume;
                }

                /**
                 * Sets the value of the volume property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setVolume(String value) {
                    this.volume = value;
                }

            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;simpleContent>
             *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
             *       &lt;attribute name="category" type="{http://www.w3.org/2001/XMLSchema}string" />
             *     &lt;/extension>
             *   &lt;/simpleContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "value"
            })
            public static class Model {

                @XmlValue
                protected String value;
                @XmlAttribute(name = "category")
                protected String category;

                /**
                 * Gets the value of the value property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getValue() {
                    return value;
                }

                /**
                 * Sets the value of the value property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setValue(String value) {
                    this.value = value;
                }

                /**
                 * Gets the value of the category property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getCategory() {
                    return category;
                }

                /**
                 * Sets the value of the category property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setCategory(String value) {
                    this.category = value;
                }

            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;simpleContent>
             *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
             *       &lt;attribute name="currency" type="{http://www.w3.org/2001/XMLSchema}string" />
             *     &lt;/extension>
             *   &lt;/simpleContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "value"
            })
            public static class Price {

                @XmlValue
                protected String value;
                @XmlAttribute(name = "currency")
                protected String currency;

                /**
                 * Gets the value of the value property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getValue() {
                    return value;
                }

                /**
                 * Sets the value of the value property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setValue(String value) {
                    this.value = value;
                }

                /**
                 * Gets the value of the currency property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getCurrency() {
                    return currency;
                }

                /**
                 * Sets the value of the currency property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setCurrency(String value) {
                    this.currency = value;
                }

            }

        }

    }

}
