//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.07.03 at 01:14:11 AM GMT+02:00 
//


package by.it.luksha.jd02_09.taskB;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the by.it_academy.luksha.xml.carrent package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: by.it_academy.luksha.xml.carrent
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CarRent }
     * 
     */
    public CarRent createCarRent() {
        return new CarRent();
    }

    /**
     * Create an instance of {@link CarRent.ListCars }
     * 
     */
    public CarRent.ListCars createCarRentListCars() {
        return new CarRent.ListCars();
    }

    /**
     * Create an instance of {@link CarRent.ListCars.Car }
     * 
     */
    public CarRent.ListCars.Car createCarRentListCarsCar() {
        return new CarRent.ListCars.Car();
    }

    /**
     * Create an instance of {@link CarRent.Address }
     * 
     */
    public CarRent.Address createCarRentAddress() {
        return new CarRent.Address();
    }

    /**
     * Create an instance of {@link CarRent.ListCars.Car.Price }
     * 
     */
    public CarRent.ListCars.Car.Price createCarRentListCarsCarPrice() {
        return new CarRent.ListCars.Car.Price();
    }

    /**
     * Create an instance of {@link CarRent.ListCars.Car.Model }
     * 
     */
    public CarRent.ListCars.Car.Model createCarRentListCarsCarModel() {
        return new CarRent.ListCars.Car.Model();
    }

    /**
     * Create an instance of {@link CarRent.ListCars.Car.Engine }
     * 
     */
    public CarRent.ListCars.Car.Engine createCarRentListCarsCarEngine() {
        return new CarRent.ListCars.Car.Engine();
    }

    /**
     * Create an instance of {@link CarRent.Address.Geoaddress }
     * 
     */
    public CarRent.Address.Geoaddress createCarRentAddressGeoaddress() {
        return new CarRent.Address.Geoaddress();
    }

    /**
     * Create an instance of {@link CarRent.Address.Webaddress }
     * 
     */
    public CarRent.Address.Webaddress createCarRentAddressWebaddress() {
        return new CarRent.Address.Webaddress();
    }

}
