//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.07.03 at 01:14:11 AM GMT+02:00 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://luksha.it-academy.by/xml/CarRent", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package by.it.luksha.jd02_09.taskB;
