//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.07.03 at 08:44:21 PM EET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://TaskC.jd02_09.kust.it.by", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package by.it.kust.jd02_09.TaskC;
