CREATE TABLE User (
ID INT AUTO_INCREMENT ,
Login VARCHAR(50) NOT NULL ,
Password VARCHAR(50) NOT NULL ,
Name VARCHAR(50) NOT NULL ,
Email VARCHAR(50) NOT NULL ,
FK_Role INT(11) NOT NULL,
PRIMARY KEY (ID)
);