//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.29 at 11:13:05 AM MSK 
//


package by.it.sinkevich.jd02_09.taskC;

import javax.xml.bind.annotation.*;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="HorseRace">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;all>
 *                   &lt;element name="Clients" type="{http://jd02_09.sinkevich.it.by}Clients"/>
 *                   &lt;element name="Races" type="{http://jd02_09.sinkevich.it.by}Races"/>
 *                   &lt;element name="BookMaker" type="{http://jd02_09.sinkevich.it.by}BookMaker"/>
 *                   &lt;element name="Horses" type="{http://jd02_09.sinkevich.it.by}Horses"/>
 *                 &lt;/all>
 *                 &lt;attribute name="date" use="required" type="{http://www.w3.org/2001/XMLSchema}date" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "horseRace"
})
@XmlRootElement(name = "HorseRaces")
public class HorseRaces {

    @XmlElement(name = "HorseRace", required = true)
    protected HorseRaces.HorseRace horseRace;

    /**
     * Gets the value of the horseRace property.
     * 
     * @return
     *     possible object is
     *     {@link HorseRaces.HorseRace }
     *     
     */
    public HorseRaces.HorseRace getHorseRace() {
        return horseRace;
    }

    /**
     * Sets the value of the horseRace property.
     * 
     * @param value
     *     allowed object is
     *     {@link HorseRaces.HorseRace }
     *     
     */
    public void setHorseRace(HorseRaces.HorseRace value) {
        this.horseRace = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;all>
     *         &lt;element name="Clients" type="{http://jd02_09.sinkevich.it.by}Clients"/>
     *         &lt;element name="Races" type="{http://jd02_09.sinkevich.it.by}Races"/>
     *         &lt;element name="BookMaker" type="{http://jd02_09.sinkevich.it.by}BookMaker"/>
     *         &lt;element name="Horses" type="{http://jd02_09.sinkevich.it.by}Horses"/>
     *       &lt;/all>
     *       &lt;attribute name="date" use="required" type="{http://www.w3.org/2001/XMLSchema}date" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {

    })
    public static class HorseRace {

        @XmlElement(name = "Clients", required = true)
        protected Clients clients;
        @XmlElement(name = "Races", required = true)
        protected Races races;
        @XmlElement(name = "BookMaker", required = true)
        protected BookMaker bookMaker;
        @XmlElement(name = "Horses", required = true)
        protected Horses horses;
        @XmlAttribute(name = "date", required = true)
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar date;

        /**
         * Gets the value of the clients property.
         * 
         * @return
         *     possible object is
         *     {@link Clients }
         *     
         */
        public Clients getClients() {
            return clients;
        }

        /**
         * Sets the value of the clients property.
         * 
         * @param value
         *     allowed object is
         *     {@link Clients }
         *     
         */
        public void setClients(Clients value) {
            this.clients = value;
        }

        /**
         * Gets the value of the races property.
         * 
         * @return
         *     possible object is
         *     {@link Races }
         *     
         */
        public Races getRaces() {
            return races;
        }

        /**
         * Sets the value of the races property.
         * 
         * @param value
         *     allowed object is
         *     {@link Races }
         *     
         */
        public void setRaces(Races value) {
            this.races = value;
        }

        /**
         * Gets the value of the bookMaker property.
         * 
         * @return
         *     possible object is
         *     {@link BookMaker }
         *     
         */
        public BookMaker getBookMaker() {
            return bookMaker;
        }

        /**
         * Sets the value of the bookMaker property.
         * 
         * @param value
         *     allowed object is
         *     {@link BookMaker }
         *     
         */
        public void setBookMaker(BookMaker value) {
            this.bookMaker = value;
        }

        /**
         * Gets the value of the horses property.
         * 
         * @return
         *     possible object is
         *     {@link Horses }
         *     
         */
        public Horses getHorses() {
            return horses;
        }

        /**
         * Sets the value of the horses property.
         * 
         * @param value
         *     allowed object is
         *     {@link Horses }
         *     
         */
        public void setHorses(Horses value) {
            this.horses = value;
        }

        /**
         * Gets the value of the date property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getDate() {
            return date;
        }

        /**
         * Sets the value of the date property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setDate(XMLGregorianCalendar value) {
            this.date = value;
        }

    }

}
