//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.29 at 11:13:05 AM MSK 
//


package by.it.sinkevich.jd02_09.taskC;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the by.it.sinkevich.jd02_09 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: by.it.sinkevich.jd02_09
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link HorseRaces }
     * 
     */
    public HorseRaces createHorseRaces() {
        return new HorseRaces();
    }

    /**
     * Create an instance of {@link HorseRaces.HorseRace }
     * 
     */
    public HorseRaces.HorseRace createHorseRacesHorseRace() {
        return new HorseRaces.HorseRace();
    }

    /**
     * Create an instance of {@link Bet }
     * 
     */
    public Bet createBet() {
        return new Bet();
    }

    /**
     * Create an instance of {@link Races }
     * 
     */
    public Races createRaces() {
        return new Races();
    }

    /**
     * Create an instance of {@link Race }
     * 
     */
    public Race createRace() {
        return new Race();
    }

    /**
     * Create an instance of {@link Horse }
     * 
     */
    public Horse createHorse() {
        return new Horse();
    }

    /**
     * Create an instance of {@link BookMaker }
     * 
     */
    public BookMaker createBookMaker() {
        return new BookMaker();
    }

    /**
     * Create an instance of {@link Horses }
     * 
     */
    public Horses createHorses() {
        return new Horses();
    }

    /**
     * Create an instance of {@link Clients }
     * 
     */
    public Clients createClients() {
        return new Clients();
    }

    /**
     * Create an instance of {@link Client }
     * 
     */
    public Client createClient() {
        return new Client();
    }

    /**
     * Create an instance of {@link Bets }
     * 
     */
    public Bets createBets() {
        return new Bets();
    }

    /**
     * Create an instance of {@link Winner }
     * 
     */
    public Winner createWinner() {
        return new Winner();
    }

}
